package hibernate;
// Generated 2022-01-18 09:49:14 by Hibernate Tools 4.3.1



/**
 * Blake generated by hbm2java
 */
public class Blake  implements java.io.Serializable {


     private String text;
     private String hash;

    public Blake() {
    }
	
    public Blake(String text) {
        this.text = text;
    }
    public Blake(String text, String hash) {
       this.text = text;
       this.hash = hash;
    }
   
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }
    
}


